---
- name: Clean up servers
  hosts: run2
  gather_facts: no
  tasks:
       - name: Delete python script file
         file:
           path: /root/dnsproject/convert_\ arrow_to_parquet.py
           state: absent
       - name: Delete folder
         file:
           path: /root/dnsproject/dnsproject
           state: absent
