---
- name: Deploy Node Exporter
  hosts: node_exporters
  become: yes
  tasks:
    - name: Download node_exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v1.7.0/node_exporter-1.7.0.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter.tar.gz"
        validate_certs: yes

    - name: Extract node_exporter
      unarchive:
        src: "/tmp/node_exporter.tar.gz"
        dest: "/opt/"
        remote_src: yes

    - name: Copy node_exporter binary to /usr/local/bin
      copy:
        src: "/opt/node_exporter-1.7.0.linux-amd64/node_exporter"
        dest: "/usr/local/bin/node_exporter"
        mode: '0755'
        remote_src: yes

    - name: Create a systemd service file for node_exporter
      template:
        src: node_exporter.service.j2
        dest: /etc/systemd/system/node_exporter.service

    - name: Enable and start node_exporter
      systemd:
        name: node_exporter
        enabled: yes
        state: started
