---
- name: Fetch a file from remote servers with unique names
  hosts: runall
  tasks:
     - name: Fetch file
       fetch:
        src: ~/processed_dns_output.parquet
        dest: "/root/refresh/{{ inventory_hostname }}_processed_dns_lookup.parquet"
        flat: yes

