---
- name: Fetch a file from remote servers with unique names
  hosts: run2
  tasks:
     - name: Fetch file
       fetch:
        src: ~/domains_all.parquet
        dest: "/root/refresh/{{ inventory_hostname }}_domains_all_refresh.parquet"
        flat: yes

