---
- name: Fetch a file from remote servers with unique names
  hosts: run2
  tasks:
     - name: Delete domains_all.parquet file
       file:
        path: /root/dnsproject/domains_all.parquet
        state: absent
     - name: Execute the Python script within venv on servers
       ansible.builtin.shell:
        cmd: |
          source ~/dnsenv/bin/activate
          nohup python ~/dnsproject/convert_arrow_to_parquet.py > /root/dnsproject/output.log 2>&1 &
       args:
         executable: /bin/bash
       async: 60
       poll: 0
       register: shell_out  
                
     - name: Display shell task details
       debug:
         var: shell_out

