---
- name: NFS Server Configuration Playbook
  hosts: contabox
  become: true
  vars:
    nfs_shared_dir: "/srv/nfs/shared"
    nfs_export_options: "(rw,sync,no_subtree_check)"
    allowed_clients:
      - "10.0.0.0/22"

  tasks:
    - name: Install NFS server packages
      ansible.builtin.apt:
        name: nfs-kernel-server
        state: present
        update_cache: yes

    - name: Create NFS shared directory and set permissions
      ansible.builtin.file:
        path: "{{ nfs_shared_dir }}"
        state: directory
        owner: nobody
        group: nogroup
        mode: '2777'  # '2' is for setgid
        recurse: yes  # Apply owner/group/mode to existing content

    - name: Configure NFS exports safely with blockinfile
      ansible.builtin.blockinfile:
        path: /etc/exports
        create: yes
        block: |
          {% for client in allowed_clients %}
          {{ nfs_shared_dir }}    {{ client }}{{ nfs_export_options }}
          {% endfor %}
      notify: Restart NFS server

  handlers:
    - name: Restart NFS server
      ansible.builtin.service:
        name: nfs-kernel-server
        state: restarted

