---
- hosts: slaves
  gather_facts: no
  tasks:
    - name: Generate SSH key pair on control machine if not exists
      local_action:
        module: openssh_keypair
        path: ~/.ssh/id_rsa
        type: rsa
        size: 4096
      run_once: true
      
    - name: Remove old known_hosts entry (if exists)
      local_action: command ssh-keygen -R {{ ansible_host }}
      failed_when: false
      changed_when: false

    - name: Install OpenSSH if not already installed
      become: yes
      apt:
        name: openssh-server
        state: present

    - name: Ensure .ssh directory exists
      become: yes
      file:
        path: /{{ ansible_user }}/.ssh
        state: directory
        mode: 0700
        owner: "{{ ansible_user }}"
        group: "{{ ansible_user }}"

    - name: Copy the SSH public key to the slave servers
      become: yes
      authorized_key:
        user: "{{ ansible_user }}"
        state: present
        key: "{{ lookup('file', '/{{ ansible_user }}/.ssh/id_rsa.pub') }}"
