---
- name: Set up SSH keys on multiple Ubuntu servers
  hosts: run1
  gather_facts: no
  vars:
    local_user: peter
  tasks:
    - name: Remove old SSH key from known_hosts
      command: ssh-keygen -f "/home/{{ local_user}}/.ssh/known_hosts" -R "{{ item }}"
      loop: "{{ groups['run1'] | map('extract', hostvars, ['ansible_host']) | list }}"

    - name: Copy new SSH key to the servers
      local_action:
        module: command
        args:
          cmd: ssh-copy-id -i /home/{{ local_user}}/.ssh/id_rsa.pub root@{{ item }}
      loop: "{{ groups['run1'] | map('extract', hostvars, ['ansible_host']) | list }}"
