---
- name: update scripts on slave servers
  hosts: slaves # Define your inventory group for slave servers
  become: yes
  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /root/celery_project
- name: update scripts on slave servers
  hosts: slaves # Define your inventory group for slave servers
  become: yes
  tasks:
    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /root/celery_project/

    - name: Clone latest Git repository
      ansible.builtin.git:
        repo: 'git@github.com:peterchap/celery_app.git'
        dest: "~/celery_project/"
        clone: True

    - name: Setup python virtual environment
      ansible.builtin.pip:
        name: setuptools
        virtualenv: ~/celery_project/celeryapp
        virtualenv_command: python3.13 -m venv

    - name: Install pip packages
      ansible.builtin.pip:
        requirements: ~/celery_project/requirements.txt
        virtualenv: ~/celeryapp
