---
- name: Create and set permissions for unbound log directory
  file:
    path: /var/log/unbound
    state: directory
    mode: '0755'
  become: true

- name: Create unbound log file and set ownership
  file:
    path: /var/log/unbound/unbound.log
    state: touch
    owner: unbound
    group: unbound
  become: true

- name: Set ownership for Unbound log file
  file:
    path: /var/log/unbound/unbound.log
    owner: unbound
    group: unbound
    state: file
  become: true

- name: Modify AppArmor for unbound logging
  blockinfile:
    path: /etc/apparmor.d/local/usr.sbin.unbound
    block: |
      /var/log/unbound/unbound.log rw,
  become: true

- name: Configure unbound
  template:
    src: unbound.conf.j2
    dest: /etc/unbound/unbound.conf
  become: true

- name: Check Unbound configuration for errors
  ansible.builtin.shell: "unbound-checkconf /etc/unbound/unbound.conf"
  register: unbound_check
  ignore_errors: yes

- name: Report Unbound configuration check status
  ansible.builtin.debug:
    msg: "Unbound configuration check: {{ 'OK' if unbound_check.rc == 0 else 'FAILED' }}"

- name: Restart Unbound service if configuration is OK
  ansible.builtin.service:
    name: unbound
    state: restarted
  when: unbound_check.rc == 0

- name: Fail the play if Unbound configuration check failed
  ansible.builtin.fail:
    msg: "Unbound configuration check failed. Please review the configuration file."
  when: unbound_check.rc != 0

