---
- name: Authenticate GitHub CLI
  ansible.builtin.shell: |
    echo "{{ github_token }}" | gh auth login --with-token
  args:
    executable: /bin/bash
- name: Debug GitHub CLI authentication
  ansible.builtin.command: gh auth status
  register: gh_auth_status

- name: Debug GitHub CLI authentication status
  ansible.builtin.debug:
    var: gh_auth_status.stdout_lines
