---
#- name: Update apt cache and upgrade
#  ansible.builtin.apt:
#    update_cache: true
#    upgrade: dist

- name: Install unbound
  ansible.builtin.apt:
    name: unbound
    state: present
