---
#- name: Update apt cache and upgrade
#  ansible.builtin.apt:
#    update_cache: true
#    upgrade: dist

- name: Install unbound
  ansible.builtin.apt:
    name: unbound
    state: present

- name: Install git
  ansible.builtin.apt:
    name: git
    state: present

- name: Install netstats
  ansible.builtin.apt:
    name: net-tools
    state: present

- name: Install unzip
  ansible.builtin.apt:
    name: unzip
    state: present
