---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
    state: present

- name: Add deadsnakes PPA GPG key manually
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6A755776
    state: present

- name: Refresh GitHub CLI GPG key
  ansible.builtin.shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
  become: yes

- name: Add deadsnakes PPA repository
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Update apt cache after adding PPA
  ansible.builtin.apt:
    update_cache: yes

- name: Install python 3.13
  ansible.builtin.apt:
    name:
      - python3.13
      - python3.13-venv     
    state: present
    update_cache: yes
    
- name: Ensure PyJWT is installed for GitHub App authentication
  pip:
    name: PyJWT
    state: present
    executable: pip3
