---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - gnupg
      - sshpass
      - python3-jwt
      - python3-pip         # Installs pip for the system Python
      - python3-venv        # Good practice to have for virtual environments
      - python3-cryptography # Installs the required 'cryptography' library
      - python3-openssl     # Often a required dependency for cryptography
    state: present

- name: Add deadsnakes PPA GPG key manually
  ansible.builtin.apt_key:
    url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x6A755776
    state: present

- name: Refresh GitHub CLI GPG key
  ansible.builtin.shell: |
    curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | sudo tee /usr/share/keyrings/githubcli-archive-keyring.gpg > /dev/null
  become: yes

- name: Add deadsnakes PPA repository
  ansible.builtin.apt_repository:
    repo: 'ppa:deadsnakes/ppa'
    state: present

- name: Update apt cache after adding PPA
  ansible.builtin.apt:
    update_cache: yes

- name: Install python 3.13
  ansible.builtin.apt:
    name:
      - python3.13
      - python3.13-venv     
    state: present
    update_cache: yes
