---
- name: Clone latest Git dnsproject repository
  ansible.builtin.git:
    repo: 'git@github.com:peterchap/dnsproject.git'
    dest: "~/dnsproject"
    update: yes
- name: Install requirements from requirements.txt
  pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv
    state: latest


