---
- name: Clone latest Git repository
  ansible.builtin.git:
    repo: 'https://github.com/peterchap/dnsproject.git'
    dest: "~/dnsproject"
    clone: true
    force: true
- name: Install requirements from requirements.txt
  pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv
    state: latest


