---
# Set up Celery on slave servers
# Set up Celery on slave servers
- name: Create Celery systemd service file for worker
  copy:
    dest: /etc/systemd/system/celery_worker.service
    content: |
      [Unit]
      Description=Celery Worker
      After=network.target
      
      [Service]
      Type=simple
      User=root
      Group=root
      WorkingDirectory=/root/celery_project
      Environment="PATH=/root/celery_project/celeryapp/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
      ExecStart=/root/celery_project/celeryapp/bin/celery -A celery_app worker --loglevel=info -Q file_queue
      StandardOutput=file:/root/celery_project/celery_worker.log
      StandardError=file:/root/celery_project/celery_worker_error.log
      Restart=always
      RestartSec=10
      
      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd to apply the new service
  systemd:
    daemon_reload: yes

- name: Enable and start the Celery worker service
  systemd:
    name: celery_worker
    enabled: yes
    state: started
