---
# Set up Celery on slave servers
- name: Create Celery systemd service file for worker
  copy:
    dest: /etc/systemd/system/celery_worker.service
    content: |
      [Unit]
      Description=Celery Worker
      After=network.target

      [Service]
      User=root
      Group=root
      WorkingDirectory=/root/celery_project/
      ExecStart=/bin/bash -c 'source /root/celery_project/celeryapp/bin/activate && celery -A celery_app worker --loglevel=info -Q file_queue'

      # Correct redirection of logs
      StandardOutput=file:/root/celery_app/celery_worker.log
      StandardError=file:/root/celery_app/celery_worker_error.log

      Restart=always
      RestartSec=10

      [Install]
      WantedBy=multi-user.target
    mode: '0644'

- name: Reload systemd to apply the new service
  systemd:
    daemon_reload: yes

- name: Enable and start the Celery worker service
  systemd:
    name: celery_worker
    enabled: yes
    state: started
