---
- name: NFS Client Configuration Playbook
  vars:
    nfs_master_server: "10.0.0.9"      # IP address of the master server
    nfs_shared_remote_dir: "/srv/nfs/shared/"  # Shared directory on the master server
    nfs_mount_point: "/mnt/shared/"            # Mount point on slave servers
    nfs_mount_options: "defaults,_netdev,noatime,hard,intr,timeo=600,retrans=2,rsize=65536,wsize=65536"
    
- name: Install NFS client packages
  ansible.builtin.apt:
    name: nfs-common
    state: present
    update_cache: yes

- name: Create mount point directory
  file:
    path: "{{ nfs_mount_point }}"
    state: directory
    owner: root
    group: root
    mode: '0755'

- name: Mount NFS share and ensure it is mounted on boot
  ansible.posix.mount:
    src: "{{ nfs_master_server }}:{{ nfs_shared_remote_dir }}"
    path: "{{ nfs_mount_point }}"
    fstype: nfs
    opts: "{{ nfs_mount_options }}"
    state: mounted
    dump: 0
    passno: 0

- name: Test write access to NFS share
  ansible.builtin.file:
    path: "{{ nfs_mount_point }}/testfile_ansible.txt"
    state: touch
  register: test_write_access
  failed_when: test_write_access is failed or ('Permission denied' in test_write_access.stderr | default(''))

- name: Remove test file from NFS share
  ansible.builtin.file:
    path: "{{ nfs_mount_point }}/testfile_ansible.txt"
    state: absent
  when: test_write_access.changed

- name: Display success message
  ansible.builtin.debug:
    msg: "NFS share {{ nfs_master_server }}:{{ nfs_shared_remote_dir }} mounted successfully on {{ nfs_mount_point }}"
