---
- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - git
      - python3.11
      - python3.11-venv
    state: present

- name: Install dead snakes for the latest python version
  ansible.builtin.shell: add-apt-repository ppa:deadsnakes/ppa -y
  register: result
 
- name: Install python 3.11
  ansible.builtin.apt:
    name:
      - python3.11
      - python3.11-venv
    state: present

- name: Clone Git repository
  ansible.builtin.git:
    repo: 'https://github.com/peterchap/dnsproject.git'
    dest: "~/dnsproject"
    clone: true

- name: Setup python virtual environment
  ansible.builtin.pip:
    name: setuptools
    virtualenv: ~/dnsenv
    virtualenv_command: python3.12 -m venv

- name: Install pip packages
  ansible.builtin.pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv

# Add any other necessary tasks related to your Python script
