---
# Setup virtual environments and download github repositories
    
- name: Clone dnsproject Git repository
  ansible.builtin.git:
    repo: 'git@github.com:peterchap/dnsproject.git'
    dest: "~/dnsproject/"
    clone: True

  - name: Setup dnsenv virtual environment
    ansible.builtin.pip:
      name: setuptools
      virtualenv: ~/dnsenv
      virtualenv_command: python3.12 -m venv

  - name: Install dnsproject module requirements
    ansible.builtin.pip:
      requirements: ~/dnsproject/requirements.txt
      virtualenv: ~/dnsenv

- name: Clone Celery_App Git repository
  ansible.builtin.git:
    repo: 'git@github.com:peterchap/celery_app.git'
    dest: "~/celery_app/"
    clone: True

  - name: Setup celeryapp virtual environment
    ansible.builtin.pip:
      name: setuptools
      virtualenv: ~/celeryapp
      virtualenv_command: python3.12 -m venv

  - name: Install celery_app module requirements
    ansible.builtin.pip:
      requirements: ~/celery_app/requirements.txt
      virtualenv: ~/celeryapp
    
