---
- name: Setup virtual environments and download github repositories
  vars:
    venv_dnspath: ~/dnsenv
    venv_celpath: ~/
- name: Create new dnsenv virtual environment using Python 3.12
  command: python3.12 -m venv "{{ venv_path }}"

- name: Install requirements from requirements.txt
  pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv
    state: latest

- name: Create new celery_app virtual environment using Python 3.12
  command: python3.12 -m venv "{{ venv_path }}"

- name: Install requirements from requirements.txt
  pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv
    state: latest
