---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes

- name: Install necessary packages
  ansible.builtin.apt:
    name:
      - software-properties-common
      - git
    state: present

- name: Add dead snakes for the latest python version
  ansible.builtin.apt_repository:
    repo: ppa:deadsnakes/ppa

- name: Update apt cache again after adding PPA
  ansible.builtin.apt:
    update_cache: yes
 
- name: Install python 3.12 and venv
  ansible.builtin.apt:
    name:
      - python3.12
      - python3.12-venv
    state: present

- name: Clone GitHub repository using GitHub CLI
  ansible.builtin.shell: |
    gh repo clone https://github.com/peterchap/dnsproject.git ~/dnsproject
  args:
    executable: /bin/bash

- name: Create virtual environemnt
  ansible.builtin.shell:
    cmd: python3.12 -m venv ~/dnsenv
  args:
   creates: ~/dnsenv/bin/activate

- name: Install pip packages
  ansible.builtin.pip:
    requirements: ~/dnsproject/requirements.txt
    virtualenv: ~/dnsenv
