---
# tasks file for rabbitmq-server

- name: Install and setup RabbitMQ on master server
  hosts: contabox
  become: yes
  tasks:
    - name: Ensure apt packages are up to date
      apt:
        update_cache: yes

    - name: Install Erlang (RabbitMQ dependency)
      apt:
        name: erlang-nox
        state: present

    - name: Install RabbitMQ server
      apt:
        name: rabbitmq-server
        state: present
        
    - name: Ensure RabbitMQ is running and enabled
      systemd:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Deploy RabbitMQ configuration file
      template:
        src: rabbitmq.conf.j2
        dest: /etc/rabbitmq/rabbitmq.conf
        owner: rabbitmq
        group: rabbitmq
        mode: '0644'
        backup: yes
      notify: Restart RabbitMQ

    - name: Enable RabbitMQ management plugin (optional)
      rabbitmq_plugin:
        name: rabbitmq_management
        state: enabled
      when: rabbitmq_management_enabled | default(false)
      notify: Restart RabbitMQ

    - name: Ensure RabbitMQ is started and enabled
      service:
        name: rabbitmq-server
        state: started
        enabled: yes

    - name: Optionally add a new RabbitMQ user (recommended for production)
      rabbitmq_user:
        user: "myuser"
        password: "mypassword"
        vhost: "/"
        configure_priv: ".*"
        read_priv: ".*"
        write_priv: ".*"
        state: present

    - name: Ensure guest user can't connect remotely (optional security step)
      rabbitmq_user:
        user: guest
        state: absent
      when: ansible_hostname != "localhost"

    - name: Open RabbitMQ AMQP port in UFW
      ufw:
        rule: allow
        port: 5672
        proto: tcp
        comment: RabbitMQ AMQP
        from_ip: "{{ item }}"
      loop: "{{ rabbitmq_allowed_ips | default(['any']) }}"
      notify: Reload UFW

    - name: Open RabbitMQ Management UI port
      ufw:
        rule: allow
        port: 15672
        proto: tcp
        comment: RabbitMQ Management
        from_ip: "{{ item }}"
      loop: "{{ rabbitmq_management_ips | default([]) }}"
      when: rabbitmq_management_enabled | default(false)
      notify: Reload UFW
