---
- name: Update apt cache and install required system packages
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - sshpass
      - python3-pip         # Installs pip for the system Python
      - python3-venv        # Good practice to have for virtual environments
      - python3-cryptography # Installs the required 'cryptography' library
      - python3-openssl     # Often a required dependency for cryptography
      - git                 # Make sure git is installed
    state: present
    update_cache: yes

- name: Configure firewall
  ansible.builtin.include_tasks: firewall.yml
