#SPDX-License-Identifier: MIT-0
---
# tasks file for roles/nfs_master
- name: Install NFS server packages
  apt:
    name: nfs-kernel-server
    state: present
    update_cache: yes

- name: Create NFS shared directory with setgid for group inheritance
  file:
    path: "{{ nfs_shared_dir }}"
    state: directory
    owner: nobody
    group: nogroup
    mode: '2777'  # rwx for all, with setgid to inherit group permissions

- name: Set recursive permissions on NFS shared directory
  command: chmod -R 777 {{ nfs_shared_dir }}
  args:
    creates: "{{ nfs_shared_dir }}"  # Only applies if the directory exists
  changed_when: false

- name: Set recursive ownership on NFS shared directory
  command: chown -R nobody:nogroup {{ nfs_shared_dir }}
  changed_when: false

- name: Configure NFS exports
  copy:
    dest: /etc/exports
    content: |
      {% for client in allowed_clients %}
      {{ nfs_shared_dir }}    {{ client }}{{ nfs_export_options }}
      {% endfor %}
  notify: Restart NFS server

- name: Export NFS shares
  command: exportfs -a
  notify: Restart NFS server
  
- name: Open NFS ports in UFW
  ufw:
    rule: allow
    port: "{{ item.port }}"
    proto: "{{ item.proto }}"
    comment: "{{ item.comment }}"
    from_ip: "{{ nfs_allowed_network }}"
  loop:
    - { port: 2049, proto: tcp, comment: 'NFS' }
    - { port: 2049, proto: udp, comment: 'NFS' }
    - { port: 111, proto: tcp, comment: 'RPC portmapper' }
    - { port: 111, proto: udp, comment: 'RPC portmapper' }
  notify: Reload UFW
